local O = OneCrosshair
local function close(a,b) assert(math.abs(a-b)<1e-8,tostring(a).." ~= "..tostring(b)) end
local health, magicka = O.LowResource.New(), O.LowResource.New()
close(O.LowResource.Intensity(health,true,1000),0)
close(O.LowResource.Intensity(health,true,1090),.5)
close(O.LowResource.Intensity(health,true,1180),1)
close(O.LowResource.Intensity(magicka,true,1180),0)
close(O.LowResource.Intensity(health,false,1181),0)
close(O.LowResource.Intensity(health,true,1182),0)
assert(O.LowResource.Intensity(health,true,1227)>0)
close(O.LowResource.Intensity(health,false,1228),0)
O.LowResource.Reset({health=health,magicka=magicka},1270)
close(O.Animator.Value(magicka,1270),0)
print("PASS warning appearance: 180 ms smoothstep, independent resources, interruption and immediate reset")

local runtime=O.runtime
local s=runtime.settings
s.resources=true; s.lowResource=true; s.visibility="ALWAYS"
T.powers[1]=100; T.now=10000
Fire(EVENT_PLAYER_ACTIVATED); O.Runtime.Update(runtime)
T.powers[1]=25; T.now=10016; O.Runtime.Update(runtime)
close(runtime.ring.arcs.health.glow.color[4],0)
T.now=10106; O.Runtime.Update(runtime)
close(runtime.ring.arcs.health.glow.color[4],s.hudOpacity*.6*.5)
T.now=10196; O.Runtime.Update(runtime)
close(runtime.ring.arcs.health.glow.color[4],s.hudOpacity*.6)
T.powers[1]=26; T.now=10197; O.Runtime.Update(runtime)
close(runtime.ring.arcs.health.glow.color[4],0)
T.powers[1]=25; T.now=10200; O.Runtime.Update(runtime)
T.now=10380; O.Runtime.Update(runtime)
s.lowResource=false; T.now=10381; O.Runtime.Update(runtime)
close(runtime.ring.arcs.health.glow.color[4],0)
s.lowResource=true; T.now=10382; O.Runtime.Update(runtime)
close(runtime.ring.arcs.health.glow.color[4],0)
T.now=10562; O.Runtime.Update(runtime)
s.visibility="OFF"; T.now=10563; O.Runtime.Update(runtime)
close(runtime.ring.arcs.health.glow.color[4],0)
close(O.Animator.Value(runtime.warnings.health,T.now),0)
s.visibility="ALWAYS"; T.now=10564; O.Runtime.Update(runtime)
T.now=10800; O.Runtime.Update(runtime)
T.menu=true; T.now=10801; O.Runtime.Update(runtime)
close(O.Animator.Value(runtime.warnings.health,T.now),0)
T.menu=false; T.now=10802; O.Runtime.Update(runtime)
close(runtime.ring.arcs.health.glow.color[4],0)
Fire(EVENT_PLAYER_DEACTIVATED)
close(O.Animator.Value(runtime.warnings.health,T.now),0)
print("PASS runtime warning fade-in at 25 percent; recovery, feature Off, visibility Off, menu and deactivation reset")
