"""Bake complete curved alpha masks from Config, without runtime rasterization."""
from pathlib import Path
import re
import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
config = (ROOT / "Core/Config.lua").read_text(encoding="utf-8")
def value(name):
    return float(re.search(rf"{name}\s*=\s*([\d.]+)", config)[1])
radius, thickness, length = (value(k) for k in
                             ("resourceRadius", "resourceThickness", "resourceLength"))
extent = radius + 2.5 * thickness + 1
tile, columns, rows, steps = 256, 8, 16, 64
axis = (np.arange(tile, dtype=np.float64) + .5) * (2 * extent / tile) - extent
x, y = np.meshgrid(axis, axis)
r = np.hypot(x, y)
angle = np.abs(np.arctan2(x, -y))
span = np.pi / 2 * length / 100
feather = .7  # UI-unit transition centered on the approved boundary.
def smooth(distance):
    t = np.clip(.5 + distance / feather, 0, 1)
    return t * t * (3 - 2 * t)
def angular(fraction):
    if fraction == 0:
        return np.zeros_like(r)
    return smooth(r * np.sin(np.clip(span * fraction / 2 - angle, -np.pi/2, np.pi/2)))
def rgba(alpha):
    pixels = np.full((tile, tile, 4), 255, dtype=np.uint8)
    pixels[:, :, 3] = np.rint(np.clip(alpha, 0, 1) * 255).astype(np.uint8)
    return Image.fromarray(pixels)
for name, width in (("ArcFill", thickness), ("ArcShield", thickness + 2)):
    atlas = Image.new("RGBA", (tile * columns, tile * rows), (255, 255, 255, 0))
    radial = smooth(width / 2 - np.abs(r - radius))
    for frame in range(steps + 1):
        atlas.paste(rgba(radial * angular(frame / steps)),
                    ((frame % columns) * tile, (frame // columns) * tile))
    atlas.save(ROOT / "Assets" / f"{name}.dds", pixel_format="DXT5")
u = (r - radius - thickness / 2) / (2 * thickness)
warning = np.clip(1 - u, 0, 1) ** 2 * smooth(r - radius - thickness / 2)
rgba(warning * angular(1)).save(ROOT / "Assets/ArcWarning.dds")
(ROOT / "Rendering/ArcAssets.lua").write_text(
    "-- Generated by tools/generate_arcs.py; regenerate after geometry edits.\n"
    "OneCrosshair.ArcAssets = {\n"
    f"    radius = {radius}, thickness = {thickness}, length = {length},\n"
    f"    extent = {extent}, steps = {steps}, columns = {columns}, rows = {rows},\n"
    "}\n", encoding="utf-8")
print("Generated 2 BC3 curved atlases (2048x4096, 256x256 cells) and 256x256 warning")
